name: Build

on:
  push:
    branches:
      - dev
    tags:
      - 'v*'
  pull_request:
    branches:
      - dev

permissions:
  contents: write
  actions: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        windows-version: [windows-2019, windows-2022]

    runs-on: ${{ matrix.windows-version }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build --config Release

    - name: Archive Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: redlight-${{ matrix.windows-version }}
        path: build/Release/RedLight.exe

    - name: Release and Upload Asset
      if: matrix.windows-version == 'windows-2022' && startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: build/Release/RedLight.exe
        token: ${{ secrets.GITHUB_TOKEN }}
